name: Build and Deploy .NET Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Web_Project_Path: 'Cana House Start/Cana House Start.csproj'  # Corrected path
      DOTNET_ROOT: /usr/share/dotnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.Web_Project_Path }}

      - name: Build
        run: dotnet build ${{ env.Web_Project_Path }} --configuration Release --no-restore

      - name: Deploy
        run: dotnet publish ${{ env.Web_Project_Path }} --configuration Release --output ./publish

        # Copy CNAME file from docs folder
      - name: Copy CNAME file
        run: cp docs/CNAME ./publish/CNAME
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
